### ISSUE TITLE
Release managers to set cla:yes label

### ISSUE THREAD

**Issue by jwendell** [istio/community#381] opened 2020-07-25 14:16 UTC
Is there a way to allow release managers for a given release (e.g., 1.7) to set the `cla:yes` label without having the googlebot removing them? Or without having to ask a googler to do so?

If not, can this being considered for a future improvement?

This kind of slows down the process of handling backports to a branch release.

**Comment by brian-avery** [comment] 2020-12-07 16:29
@howardjohn any thoughts on this? Thanks!

**Comment by howardjohn** [comment] 2020-12-07 16:30
Would love to have it, but I don't know how

**Comment by sdake** [comment] 2020-12-07 17:44
l asked this question of @geeknoid. He indicated it is against Google
policy and can’t be done. Maybe things have changed.

**Comment by brian-avery** [comment] 2020-12-07 19:48
I was talking to John earlier. I think the primary concern here is that it's a black box. What we see a lot of the time: 

* Cherrypick PR opened
* Gives error that CLA hasn't been accepted
* Person reviewing cherrypick tracks down the people who made changes in the pull request
* They each add variants of "@googlebot I accept". 
* Googlebot sometimes accepts them and sometimes doesn't.

There's no visibility into why the Googlebot failed and the only recourse is to reach out to a Googler who sometimes finds the cause and sometimes just adds the label. 

I think that some level of debugging utility would get us 90% of the way there. I see: 

* why did Googlebot fail? Is it looking for something specific? If we only have to track down one person, then that likely saves quite a bit of time. 
* was it an internal failure? If we had the option to retry, then that would again help quite a bit.

**Comment by jwendell** [comment] 2020-12-08 15:12
Couldn't people just sign-off their commits for this purpose?

**Comment by craigbox** [comment] 2021-03-18 16:08
The Googlebot team has indicated that a change for automatically accepting cherrypick commits is on their roadmap.  Until then, we've been told that it's OK for Googlers to explicitly set the label.

I understand this is suboptimal for people that are non-Googlers, and I apologize; feel free to CC me on any issues that don't move quickly enough and I can set the label for you.

I'll keep https://github.com/istio/istio.io/issues/6333 open and close this one.

**Closed by craigbox** 2021-03-18 16:08 UTC
