### ISSUE TITLE
404

### ISSUE THREAD

**Issue by mcandre** [istio/community#624] opened 2021-07-19 15:30 UTC
The "https://www.envoyproxy.io/docs/envoy/latest/api-v2/api/v2/auth/cert.proto.html" link on the destination rule page appears to be dead.

https://istio.io/latest/docs/reference/config/networking/destination-rule/#ClientTLSSettings

**Comment by ericvn** [comment] 2021-08-04 14:43
Duplicate of https://github.com/istio/api/issues/2015

**Closed** 2021-08-05 02:56 UTC
