### ISSUE TITLE
Table overlap with side menu

### ISSUE THREAD

**Issue by prary** [istio/community#582] opened 2021-06-06 09:34 UTC
On medium size screen css looks to be broken, but this is fine on mobile small screen.

https://istio.io/latest/docs/reference/config/istio.mesh.v1alpha1/

![image](https://user-images.githubusercontent.com/6360614/120919597-0d1a6000-c6d8-11eb-8a85-c69499230c42.png)

I would be happy to raise a PR for it.

**Comment by ericvn** [comment] 2021-06-08 17:49
This looks to be a duplicate of https://github.com/istio/istio.io/issues/9858

**Comment by craigbox** [comment] 2021-07-11 13:59
Yep, I'll close this for that.

**Closed by craigbox** 2021-07-11 13:59 UTC
