### ISSUE TITLE
Slack invite link is broken: 2023/9/4

### ISSUE THREAD

**Issue by owlzq1** [istio/community#1199] opened 2023-09-04 15:50 UTC
Same problem as https://github.com/istio/community/issues/1123 .
https://slack.istio.io/

Istio.io slack invite link has expired.
Could you update to the new link?

**Comment by kfaseela** [comment] 2023-09-04 19:19
cc @SkyfireFrancisZ

**Comment by hzxuzhonghu** [comment] 2023-09-05 07:13
@kfaseela Seems i can update the link

**Comment by hzxuzhonghu** [comment] 2023-09-05 07:38
https://github.com/istio/istio.io/pull/13813

**Comment by craigbox** [comment] 2023-09-05 08:41
https://shipyard.build/blog/slack-community-invite-change/

> But here’s an insider tip: if you reach out to Slack support, they have been known to work with bigger communities to create a link that is good for more sign-ups!

**Comment by kfaseela** [comment] 2023-09-05 08:51
@owlzq1 let us know if the problem is fixed for you now.

**Comment by owlzq1** [comment] 2023-09-05 09:45
@kfaseela the link from the official site doesn't work https://istio.io/latest/get-involved/

**Comment by hzxuzhonghu** [comment] 2023-09-05 12:03
I think the tf job is not run

**Comment by davidwhite-nd** [comment] 2023-09-05 14:18
@kfaseela 
I just tried, and its not working for me.

**Comment by ericvn** [comment] 2023-09-05 14:33
I just tried in a private window and see this URL: https://istio.slack.com/join/shared_invite/zt-1z9yjkym8-HTFsoVo4Zom7LOwBXxjc2Q#/shared-invite/error

That is indeed the older link. I'm not sure what has to happen after the test-infra link merges. Does merging the new link cause an appropriate update in the service or does it also need restarting?

**Comment by kfaseela** [comment] 2023-09-05 14:44
@davidwhite-nd could you please use the updated invite link in the below PR directly for the time being, while we get this fixed properly in the docs? https://github.com/istio/test-infra/pull/4996

**Comment by kfaseela** [comment] 2023-09-05 15:10
@howardjohn will run the required jobs to get this in effect

**Comment by davidwhite-nd** [comment] 2023-09-05 15:13
@kfaseela - that worked! thank you.

**Comment by kfaseela** [comment] 2023-09-05 16:06
@owlzq1 : It should be fixed now, please check, and you can close the issue if resolved.

**Closed** 2023-09-06 07:22 UTC
